/*
Copyright 2024 The Kuasar Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//! Unix-socket service API for sandbox and template management.
//!
//! Listens on `--admin-listen` (default `/run/vmm-sandboxer-admin.sock`).
//! Protocol: one JSON object per line, one request/response per connection.
//!
//! ## Sandbox actions
//!
//! ### sandbox-run — create a sandbox slot and restore from template in one step
//!
//! `snapshot_type` selects the restore mode.  Each type accepts a distinct set of fields;
//! mixing fields across types is rejected.  Memory restore mode is always the server default.
//!
//! **warm_fork**:
//! ```json
//! {"action":"sandbox-run","snapshot_type":"warm_fork","template_key":"<pool-key>"}
//! {"action":"sandbox-run","snapshot_type":"warm_fork","template_id":"<id>"}
//! {"action":"sandbox-run","snapshot_type":"warm_fork","template_key":"<pool-key>","template_id":"<id>"}
//! ```
//! - `key` — pool key; latest WarmFork template for this key is restored.
//! - `template_id` — pin to a specific template by ID.
//! - At least one of `key` or `template_id` is required. When both are provided they must match.
//! - Runs in autonomous mode: `task_id = None`, process self-starts after COMMIT.
//! - Snapshot-time targets (container_id, socket_path) are taken from the template.
//!
//! **continuation**:
//! ```json
//! {"action":"sandbox-run","snapshot_type":"continuation","pod_uid":"<uid>","generation":0}
//! ```
//! - `pod_uid` required — uniquely identifies the workload instance.
//! - `generation` optional — defaults to 0.
//! - Network identity must be migrated externally before calling this.
//!
//! Response: `{"ok":true,"sandbox_id":"<id>","template_id":"<id>"}`
//!
//! ### sandbox-destroy — stop a sandbox and release all resources
//! ```json
//! {"action":"sandbox-destroy","sandbox_id":"<id>"}
//! ```
//! Stops the VM, releases the template lease, and deletes the sandbox directory.
//! Works for both `run`-created sandboxes and containerd-managed sandboxes that are stopped.
//!
//! ### sandbox-list — list all known sandboxes
//! ```json
//! {"action":"sandbox-list"}
//! ```
//! Response: `{"ok":true,"sandboxes":[{"id":"<id>","status":"<status>","base_dir":"<dir>","template_id":"<id>","template_snapshot_type":"<type>"},...]}`
//!
//! ### sandbox-get — get details of a single sandbox
//! ```json
//! {"action":"sandbox-get","sandbox_id":"<id>"}
//! ```
//! Response includes additional fields: `lease_mode`, `memory_restore_mode`.
//!
//! ## Template actions
//!
//! ### template-create — snapshot a running sandbox into the template pool
//! ```json
//! {"action":"template-create","sandbox_id":"<id>","key":"<pool-key>"}
//! {"action":"template-create","sandbox_id":"<id>","key":"<pool-key>","snapshot_type":"warm_fork"}
//! {"action":"template-create","sandbox_id":"<id>","snapshot_type":"continuation","pod_uid":"<uid>","generation":0}
//! ```
//! - `template_id`      ignored if supplied — generated by the server.
//! - `key`     **required for WarmFork** — pool key; pods with `kuasar.io/template-key=<key>` will match.
//!                      **ignored for Continuation** — key is auto-derived from `pod_uid:generation`.
//! - `snapshot_type`    optional — `"warm_fork"` (default) or `"continuation"`.
//! - `pod_uid`          required when `snapshot_type=continuation` — uniquely identifies the workload instance.
//! - `generation`  optional when `snapshot_type=continuation` — defaults to 0.
//!
//! **WarmFork**: the sandbox process must be in ready-waiting state (blocking on the readiness socket)
//! and the pod must carry `kuasar.io/warm-fork-ready-protocol-version=v1`.
//! Restore: pod must set `kuasar.io/template-key=<key>` matching the key used here.
//!
//! **Continuation**: captures the process as-is (no ready-waiting state required). Pool key is
//! `{pod_uid}:{generation}`. The pod must set
//! `kuasar.io/pod-uid=<uid>` and optionally
//! `kuasar.io/workload-generation=<n>` for the restore path to find this template.
//! Network identity transfer to the target node is the operator's responsibility before restore.
//!
//! ### template-list / template-get — inspect available templates
//! ```json
//! {"action":"template-list"}
//! {"action":"template-get","template_id":"<id>"}
//! ```
//! Lists or returns available Environment/WarmFork templates from the pool and available
//! Continuation entries from the continuation store.
//!
//! ### template-from-bundle — (not yet implemented)
//! ```json
//! {"action":"template-from-bundle","bundle_dir":"<path>","template_id":"<id>","key":"<pool-key>"}
//! ```
//! Returns an actionable error until containerd/snapshotter integration is available.
//!
//! ### pool-status — query pool health and metrics
//! ```json
//! {"action":"pool-status"}
//! ```
//!
//! ### pool-refill — spawn background environment-VM refill tasks
//! ```json
//! {"action":"pool-refill","kind":"environment","target_depth":3}
//! ```
//! - `kind`          required; only `"environment"` is supported (WarmFork/Continuation require additional info not available here)
//! - `target_depth`  refill up to this many templates (existing + in-flight count toward the target)
//!
//! ### pool-gc — remove a single template from the pool by ID
//! ```json
//! {"action":"pool-gc","kind":"environment","template_id":"<id>"}
//! ```
//! - `kind`          `"environment"` or `"warm_fork"` (required, safety cross-check against the template's actual kind)
//! - `template_id`   ID of the template to remove (required)
//!
//! ## Response envelope
//! ```json
//! {"ok":true,...}
//! {"ok":false,"error":"<message>"}
//! ```

use std::{
    collections::HashMap, io::ErrorKind, os::unix::fs::PermissionsExt, path::PathBuf, sync::Arc,
};

use anyhow::anyhow;
use containerd_sandbox::{
    data::SandboxData, error::Result, signal::ExitSignal, utils::cleanup_mounts, SandboxOption,
    SandboxStatus,
};
use log::{error, info, warn};
use serde_json::{json, Value};
use tokio::{
    fs::{create_dir_all, remove_dir_all},
    io::{AsyncBufReadExt, AsyncWrite, AsyncWriteExt, BufReader},
    net::{UnixListener, UnixStream},
    sync::{Mutex, RwLock},
};

use crate::{
    cgroup::SandboxCgroup,
    sandbox::{
        create_template_worker, monitor, parse_warm_fork_container_names, KuasarSandbox,
        MemoryRestoreMode, SnapshotConfig, TemplateLeaseMode,
    },
    storage::device_graph::DeviceGraph,
    template::{
        new_template_id, ContinuationStore, CreateTemplateRequest, PooledTemplate,
        SnapshotContainerMeta, SnapshotType, TemplateKey, TemplateLease, TemplatePool,
        WorkloadIdentity,
    },
    vm::{
        DiskSnapshot, RestoreSource, SnapshotPathOverrides, Snapshottable, VMFactory,
        WarmForkParams, WarmForkTarget, ANNOTATION_WARM_FORK_CONTAINERS,
        ANNOTATION_WARM_FORK_DEFAULT_READINESS_SOCKET, ANNOTATION_WARM_FORK_READINESS_SOCKET,
        ANNOTATION_WARM_FORK_READY_PROTOCOL, VIRTIO_BLK, VM, WARM_FORK_PROTOCOL_V1,
    },
};

/// Shared state extracted from `KuasarSandboxer` for the service server.
/// All fields are cheaply cloneable via `Arc`.
pub struct Handle<F>
where
    F: VMFactory + Sync + Send + 'static,
    F::VM: VM + Snapshottable + Sync + Send + 'static,
{
    pub factory: Arc<F>,
    #[allow(clippy::type_complexity)]
    pub sandboxes: Arc<RwLock<HashMap<String, Arc<Mutex<KuasarSandbox<F::VM>>>>>>,
    pub pool: Option<Arc<TemplatePool>>,
    pub continuation_store: Option<Arc<ContinuationStore>>,
    pub snapshot_config: SnapshotConfig,
    /// Root directory for sandbox slots created by the `run` action.
    /// Set to `<sandboxer --dir>/`.
    pub sandbox_base_dir: PathBuf,
}

/// Listens on a Unix socket and dispatches sandbox and template management commands.
pub struct Server<F>
where
    F: VMFactory + Sync + Send + 'static,
    F::VM: VM + Snapshottable + Sync + Send + 'static,
{
    handle: Arc<Handle<F>>,
    sock_path: PathBuf,
}

impl<F> Server<F>
where
    F: VMFactory + Sync + Send + 'static,
    F::VM: VM + Snapshottable + Sync + Send + 'static,
{
    pub fn new(handle: Handle<F>, sock_path: impl Into<PathBuf>) -> Self {
        Self {
            handle: Arc::new(handle),
            sock_path: sock_path.into(),
        }
    }

    /// Run the admin server, accepting connections until the process exits.
    pub async fn serve(self) {
        // Remove stale socket from a previous run.
        let _ = tokio::fs::remove_file(&self.sock_path).await;

        let listener = match UnixListener::bind(&self.sock_path) {
            Ok(l) => l,
            Err(e) => {
                error!("service:failed to bind {:?}: {}", self.sock_path, e);
                return;
            }
        };
        if let Err(e) =
            std::fs::set_permissions(&self.sock_path, std::fs::Permissions::from_mode(0o600))
        {
            warn!("service:could not restrict socket permissions: {}", e);
        }
        info!("service:listening on {:?}", self.sock_path);

        loop {
            match listener.accept().await {
                Ok((stream, _)) => {
                    let handle = self.handle.clone();
                    tokio::spawn(async move {
                        if let Err(e) = handle_connection(handle, stream).await {
                            warn!("service:connection error: {}", e);
                        }
                    });
                }
                Err(e) => {
                    error!("service:accept error: {}", e);
                }
            }
        }
    }
}

/// Validate key: 1–253 chars, [a-zA-Z0-9_.-], must start and end with [a-zA-Z0-9].
fn validate_key(key: &str) -> anyhow::Result<()> {
    if key.is_empty() || key.len() > 253 {
        return Err(anyhow!("key must be 1-253 characters, got {}", key.len()));
    }
    let starts_ok = key
        .chars()
        .next()
        .is_some_and(|c| c.is_ascii_alphanumeric());
    let ends_ok = key
        .chars()
        .last()
        .is_some_and(|c| c.is_ascii_alphanumeric());
    if !starts_ok || !ends_ok {
        return Err(anyhow!(
            "key '{}' must start and end with an alphanumeric character",
            key
        ));
    }
    if !key
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_' || c == '.')
    {
        return Err(anyhow!(
            "key '{}' contains invalid characters (only [a-zA-Z0-9_.-] allowed)",
            key
        ));
    }
    Ok(())
}

fn validate_id(id: &str) -> anyhow::Result<()> {
    if id.len() < 12 || id.len() > 64 {
        return Err(anyhow!("id must be 12-64 characters, got {}", id.len()));
    }
    if !id
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
    {
        return Err(anyhow!(
            "id '{}' contains invalid characters (only [a-zA-Z0-9_-] allowed)",
            id
        ));
    }
    Ok(())
}

/// Resolve a full sandbox ID from an exact ID.
fn resolve_sandbox_id<V>(sandboxes: &HashMap<String, V>, id: &str) -> anyhow::Result<String> {
    if sandboxes.contains_key(id) {
        Ok(id.to_string())
    } else {
        Err(anyhow!("sandbox {} not found", id))
    }
}

async fn write_json_response<W>(writer: &mut W, response: Value) -> anyhow::Result<()>
where
    W: AsyncWrite + Unpin,
{
    let mut out = serde_json::to_string(&response)?;
    out.push('\n');
    writer.write_all(out.as_bytes()).await?;
    Ok(())
}

async fn handle_connection<F>(handle: Arc<Handle<F>>, stream: UnixStream) -> anyhow::Result<()>
where
    F: VMFactory + Sync + Send + 'static,
    F::VM: VM + Snapshottable + Sync + Send + 'static,
{
    let (reader, mut writer) = stream.into_split();
    let mut lines = BufReader::new(reader).lines();

    let line = lines
        .next_line()
        .await?
        .ok_or_else(|| anyhow!("empty request"))?;

    let req: Value = serde_json::from_str(&line)?;
    let action = req["action"].as_str().unwrap_or("").to_string();

    let (category, verb) = action.split_once('-').unwrap_or((&action, ""));

    let result = match category {
        "sandbox" => match verb {
            "run" => handle_sandbox_run(&handle, &req).await,
            "destroy" => handle_sandbox_destroy(&handle, &req).await,
            "list" => handle_sandbox_list(&handle).await,
            "get" => handle_sandbox_get(&handle, &req).await,
            _ => Err(anyhow!("unknown sandbox action: sandbox-{}", verb)),
        },
        "template" => match verb {
            "create" => handle_template_create(&handle, &req).await,
            "list" => handle_template_list(&handle).await,
            "get" => handle_template_get(&handle, &req).await,
            _ => Err(anyhow!("unknown template action: template-{}", verb)),
        },
        "pool" => match verb {
            "status" => handle_pool_status(&handle).await,
            "refill" => handle_pool_refill(&handle, &req).await,
            "gc" => handle_pool_gc(&handle, &req).await,
            _ => Err(anyhow!("unknown pool action: pool-{}", verb)),
        },
        "continuation" => match verb {
            "list" => handle_continuation_list(&handle).await,
            "delete" => handle_continuation_delete(&handle, &req).await,
            _ => Err(anyhow!(
                "unknown continuation action: continuation-{}",
                verb
            )),
        },
        _ => Err(anyhow!("unknown action: {}", action)),
    };

    let response = result.unwrap_or_else(|e| json!({"ok": false, "error": e.to_string()}));
    write_json_response(&mut writer, response).await
}

async fn handle_template_create<F>(handle: &Handle<F>, req: &Value) -> anyhow::Result<Value>
where
    F: VMFactory + Sync + Send + 'static,
    F::VM: VM + Snapshottable + Sync + Send + 'static,
{
    let sandbox_id = req["sandbox_id"]
        .as_str()
        .ok_or_else(|| anyhow!("missing sandbox_id"))?
        .to_string();
    validate_id(&sandbox_id).map_err(|e| anyhow!("invalid sandbox_id: {}", e))?;
    // snapshot_type defaults to warm_fork for backward compatibility with existing callers.
    let snapshot_type = match req["snapshot_type"].as_str().unwrap_or("warm_fork") {
        "warm_fork" => SnapshotType::WarmFork,
        "continuation" => SnapshotType::Continuation,
        other => {
            return Err(anyhow!(
                "unsupported snapshot_type '{}'; use warm_fork or continuation",
                other
            ))
        }
    };

    // Continuation requires workload_identity; pool key is derived from it automatically.
    // WarmFork requires an explicit pool key.
    let (key, workload_identity) = if matches!(snapshot_type, SnapshotType::Continuation) {
        let pod_uid = req["pod_uid"]
            .as_str()
            .ok_or_else(|| {
                anyhow!(
                    "snapshot_type=continuation requires pod_uid \
                     (uniquely identifies this workload instance)"
                )
            })?
            .to_string();
        if pod_uid.is_empty() {
            return Err(anyhow!("pod_uid must not be empty"));
        }
        let generation: u32 = match req["generation"].as_u64() {
            None => 0,
            Some(v) if v <= u32::MAX as u64 => v as u32,
            Some(v) => {
                return Err(anyhow!(
                    "generation {} exceeds u32::MAX; refusing to create template \
                     (a bad generation would silently match the wrong pool key)",
                    v
                ))
            }
        };
        // Pool key is auto-derived; any user-supplied "key" field is silently ignored.
        let wi = WorkloadIdentity {
            pod_uid,
            generation,
        };
        let derived_key = wi.pod_uid.clone();
        (derived_key, Some(wi))
    } else {
        let k = req["key"]
            .as_str()
            .ok_or_else(|| anyhow!("missing key: WarmFork snapshots require a pool key"))?
            .to_string();
        validate_key(&k).map_err(|e| anyhow!("invalid key: {}", e))?;
        (k, None)
    };
    let template_id = new_template_id();
    validate_id(&template_id).map_err(|e| anyhow!("invalid template_id: {}", e))?;

    let tmpl = create_from_sandbox(
        handle,
        &sandbox_id,
        &template_id,
        &key,
        snapshot_type,
        workload_identity,
    )
    .await?;
    Ok(
        json!({"ok": true, "template_id": tmpl.id, "key": tmpl.key.key,
              "snapshot_type": snapshot_type_str(&tmpl.snapshot_type)}),
    )
}

async fn handle_sandbox_run<F>(handle: &Handle<F>, req: &Value) -> anyhow::Result<Value>
where
    F: VMFactory + Sync + Send + 'static,
    F::VM: VM + Snapshottable + Sync + Send + 'static,
{
    let snapshot_type = req
        .get("snapshot_type")
        .and_then(|v| v.as_str())
        .unwrap_or("");

    match snapshot_type {
        "warm_fork" => {
            // Reject continuation-only fields.
            if req.get("pod_uid").and_then(|v| v.as_str()).is_some()
                || req.get("generation").is_some()
            {
                return Ok(json!({
                    "ok": false,
                    "error": "snapshot_type=warm_fork does not accept pod_uid or generation"
                }));
            }
            let key = match req["template_key"].as_str() {
                Some(k) => {
                    validate_key(k).map_err(|e| anyhow!("invalid key: {}", e))?;
                    Some(k.to_string())
                }
                None => None,
            };
            let template_id = match req["template_id"].as_str() {
                Some(tid) => {
                    validate_id(tid).map_err(|e| anyhow!("invalid template_id: {}", e))?;
                    Some(tid.to_string())
                }
                None => None,
            };
            if key.is_none() && template_id.is_none() {
                return Ok(json!({
                    "ok": false,
                    "error": "snapshot_type=warm_fork requires at least one of: key, template_id"
                }));
            }
            let sandbox_id = format!(
                "{}{}",
                uuid::Uuid::new_v4().simple(),
                uuid::Uuid::new_v4().simple()
            );
            create_sandbox_slot(handle, &sandbox_id)
                .await
                .map_err(|e| anyhow!("create sandbox slot: {}", e))?;
            let tmpl_id = restore_sandbox_warm_fork(
                handle,
                &sandbox_id,
                key.as_deref(),
                template_id.as_deref(),
            )
            .await?;
            Ok(json!({"ok": true, "sandbox_id": sandbox_id, "template_id": tmpl_id}))
        }
        "continuation" => {
            // Reject environment / warm_fork fields.
            if req.get("template_id").and_then(|v| v.as_str()).is_some()
                || req.get("template_key").and_then(|v| v.as_str()).is_some()
            {
                return Ok(json!({
                    "ok": false,
                    "error": "snapshot_type=continuation only accepts pod_uid and generation; \
                              template_id and template_key are not valid for this type"
                }));
            }
            let pod_uid = match req["pod_uid"].as_str() {
                Some(uid) => uid.to_string(),
                None => {
                    return Ok(json!({
                        "ok": false,
                        "error": "snapshot_type=continuation requires pod_uid"
                    }))
                }
            };
            let generation = req["generation"].as_u64().unwrap_or(0) as u32;
            let sandbox_id = format!(
                "{}{}",
                uuid::Uuid::new_v4().simple(),
                uuid::Uuid::new_v4().simple()
            );
            create_sandbox_slot(handle, &sandbox_id)
                .await
                .map_err(|e| anyhow!("create sandbox slot: {}", e))?;
            let tmpl_id =
                restore_sandbox_continuation(handle, &sandbox_id, &pod_uid, generation).await?;
            Ok(json!({"ok": true, "sandbox_id": sandbox_id, "template_id": tmpl_id}))
        }
        other => Ok(json!({
            "ok": false,
            "error": format!(
                "unknown snapshot_type '{}'; valid values: warm_fork, continuation",
                other
            )
        })),
    }
}

async fn handle_sandbox_destroy<F>(handle: &Handle<F>, req: &Value) -> anyhow::Result<Value>
where
    F: VMFactory + Sync + Send + 'static,
    F::VM: VM + Snapshottable + Sync + Send + 'static,
{
    let sandbox_id = req["sandbox_id"]
        .as_str()
        .ok_or_else(|| anyhow!("missing sandbox_id"))?
        .to_string();
    validate_id(&sandbox_id).map_err(|e| anyhow!("invalid sandbox_id: {}", e))?;
    let full_id = {
        let sandboxes = handle.sandboxes.read().await;
        resolve_sandbox_id(&sandboxes, &sandbox_id)?
    };
    destroy_sandbox(handle, &full_id).await?;
    Ok(json!({"ok": true, "sandbox_id": full_id}))
}

async fn handle_sandbox_list<F>(handle: &Handle<F>) -> anyhow::Result<Value>
where
    F: VMFactory + Sync + Send + 'static,
    F::VM: VM + Snapshottable + Sync + Send + 'static,
{
    let sandboxes = handle.sandboxes.read().await;
    let mut items = Vec::with_capacity(sandboxes.len());
    for (id, mtx) in sandboxes.iter() {
        let sb = mtx.lock().await;
        items.push(json!({
            "id": id,
            "status": sandbox_status_str(&sb.status),
            "base_dir": sb.base_dir,
            "template_id": sb.template_id,
            "template_snapshot_type": sb.template_snapshot_type.as_ref().map(snapshot_type_str),
        }));
    }
    Ok(json!({"ok": true, "sandboxes": items}))
}

async fn handle_sandbox_get<F>(handle: &Handle<F>, req: &Value) -> anyhow::Result<Value>
where
    F: VMFactory + Sync + Send + 'static,
    F::VM: VM + Snapshottable + Sync + Send + 'static,
{
    let sandbox_id = req["sandbox_id"]
        .as_str()
        .ok_or_else(|| anyhow!("missing sandbox_id"))?;
    validate_id(sandbox_id).map_err(|e| anyhow!("invalid sandbox_id: {}", e))?;
    let sandboxes = handle.sandboxes.read().await;
    let full_id = resolve_sandbox_id(&sandboxes, sandbox_id)?;
    let mtx = sandboxes
        .get(&full_id)
        .ok_or_else(|| anyhow!("sandbox {} not found", full_id))?;
    let sb = mtx.lock().await;
    Ok(json!({
        "ok": true,
        "id": sb.id,
        "status": sandbox_status_str(&sb.status),
        "base_dir": sb.base_dir,
        "template_id": sb.template_id,
        "template_snapshot_type": sb.template_snapshot_type.as_ref().map(snapshot_type_str),
        "lease_mode": sb.lease_mode.as_ref().map(|m| format!("{}", m)),
        "memory_restore_mode": sb.memory_restore_mode.as_ref().map(|m| format!("{:?}", m)),
    }))
}

fn sandbox_status_str(status: &containerd_sandbox::SandboxStatus) -> &'static str {
    match status {
        containerd_sandbox::SandboxStatus::Created => "created",
        containerd_sandbox::SandboxStatus::Running(_) => "running",
        containerd_sandbox::SandboxStatus::Stopped(_, _) => "stopped",
        _ => "unknown",
    }
}

fn snapshot_type_str(kind: &SnapshotType) -> &'static str {
    match kind {
        SnapshotType::Environment => "environment",
        SnapshotType::WarmFork => "warm_fork",
        SnapshotType::Continuation => "continuation",
    }
}

async fn handle_pool_status<F>(handle: &Handle<F>) -> anyhow::Result<Value>
where
    F: VMFactory + Sync + Send + 'static,
    F::VM: VM + Snapshottable + Sync + Send + 'static,
{
    let pool = handle
        .pool
        .as_ref()
        .ok_or_else(|| anyhow!("template pool not configured"))?;
    let total = pool.total_depth().await;
    let keys = pool.key_count().await;
    let in_flight = pool.in_flight_count().await;
    let by_type = pool.depth_by_type().await;
    let by_key = pool.depth_by_key().await;
    let active_shared_refs = pool.active_shared_refs().await;
    let in_flight_restores = pool.in_flight_restores_by_template().await;
    let gc_blocked = pool.gc_blocked_templates().await;
    let continuation_count = if let Some(store) = &handle.continuation_store {
        store.list().await.len()
    } else {
        0
    };
    let m = &pool.metrics;
    Ok(json!({
        "ok": true,
        "total": total,
        "by_type": by_type.into_iter().map(|(t, d)| json!({"type": t, "count": d})).collect::<Vec<_>>(),
        "continuation": continuation_count,
        "keys": keys,
        "in_flight": in_flight,
        "by_key": by_key.into_iter().map(|(k, d)| json!({"key": k, "depth": d})).collect::<Vec<_>>(),
        "active_shared_refs": active_shared_refs.into_iter().map(|(id, refs)| json!({"template_id": id, "refs": refs})).collect::<Vec<_>>(),
        "in_flight_restores": in_flight_restores.into_iter().map(|(id, count)| json!({"template_id": id, "count": count})).collect::<Vec<_>>(),
        "gc_blocked": gc_blocked.into_iter().map(|(id, reason)| json!({"template_id": id, "reason": reason})).collect::<Vec<_>>(),
        "templates_created": m.templates_created.load(std::sync::atomic::Ordering::Relaxed),
        "pool_hits": m.pool_hits.load(std::sync::atomic::Ordering::Relaxed),
        "pool_misses": m.pool_misses.load(std::sync::atomic::Ordering::Relaxed),
        "hit_rate": m.hit_rate(),
        "avg_restore_ms": m.avg_restore_ms(),
    }))
}

fn template_json(t: &PooledTemplate) -> Value {
    let mut item = json!({
        "template_id": t.id,
        "snapshot_type": snapshot_type_str(&t.snapshot_type),
        "key": t.key.key,
        "created_at_secs": t.created_at_secs,
        "snapshot_dir": t.snapshot_dir,
    });
    if let Some(wi) = &t.workload_identity {
        item["pod_uid"] = wi.pod_uid.clone().into();
        item["generation"] = wi.generation.into();
    }
    item
}

async fn handle_template_list<F>(handle: &Handle<F>) -> anyhow::Result<Value>
where
    F: VMFactory + Sync + Send + 'static,
    F::VM: VM + Snapshottable + Sync + Send + 'static,
{
    let mut entries = Vec::new();
    if let Some(pool) = &handle.pool {
        entries.extend(pool.list_templates().await.iter().map(template_json));
    }
    if let Some(store) = &handle.continuation_store {
        entries.extend(store.list().await.iter().map(template_json));
    }
    entries.sort_by(|a, b| {
        a["template_id"]
            .as_str()
            .unwrap_or("")
            .cmp(b["template_id"].as_str().unwrap_or(""))
    });
    Ok(json!({"ok": true, "templates": entries}))
}

async fn handle_template_get<F>(handle: &Handle<F>, req: &Value) -> anyhow::Result<Value>
where
    F: VMFactory + Sync + Send + 'static,
    F::VM: VM + Snapshottable + Sync + Send + 'static,
{
    let template_id = req["template_id"]
        .as_str()
        .ok_or_else(|| anyhow!("missing template_id"))?;
    validate_id(template_id).map_err(|e| anyhow!("invalid template_id: {}", e))?;

    if let Some(pool) = &handle.pool {
        if let Some(t) = pool.get_template(template_id).await {
            return Ok(json!({"ok": true, "template": template_json(&t)}));
        }
    }
    if let Some(store) = &handle.continuation_store {
        if let Some(t) = store.list().await.into_iter().find(|t| t.id == template_id) {
            return Ok(json!({"ok": true, "template": template_json(&t)}));
        }
    }
    Err(anyhow!("template {} not found", template_id))
}

async fn handle_pool_refill<F>(handle: &Handle<F>, req: &Value) -> anyhow::Result<Value>
where
    F: VMFactory + Sync + Send + 'static,
    F::VM: VM + Snapshottable + Sync + Send + 'static,
{
    let pool = handle
        .pool
        .as_ref()
        .ok_or_else(|| anyhow!("template pool not configured"))?;
    let kind_str = match req["kind"].as_str() {
        Some(k) => k,
        None => return Ok(json!({"ok": false, "error": "missing required field 'kind'"})),
    };
    let target_depth = req["target_depth"].as_u64().unwrap_or(1) as usize;
    match kind_str {
        "environment" => {
            let key = TemplateKey::from_vm_config(
                handle.factory.kernel_path(),
                handle.factory.image_path(),
                handle.factory.vcpus(),
                handle.factory.memory_mb(),
                handle.factory.kernel_params(),
                handle.factory.storage_backend(),
            );
            let current = pool.depth(&key).await;
            let in_flight = pool.in_flight_count_for_key(&key).await;
            let need = target_depth.saturating_sub(current.saturating_add(in_flight));
            for _ in 0..need {
                let refill_id = new_template_id();
                let pool_c = pool.clone();
                let factory_c = Arc::clone(&handle.factory);
                pool.begin_refill(&key).await;
                let key_c = key.clone();
                tokio::spawn(async move {
                    if let Err(e) = create_template_worker(
                        factory_c,
                        pool_c.clone(),
                        CreateTemplateRequest::new_with_lease_mode(
                            refill_id,
                            pool_c.lease_mode.clone(),
                        ),
                    )
                    .await
                    {
                        warn!("refill: template creation failed: {}", e);
                    }
                    pool_c.end_refill(&key_c).await;
                });
            }
            let new_in_flight = pool.in_flight_count_for_key(&key).await;
            Ok(
                json!({"ok": true, "kind": "environment", "queued": need, "in_flight": new_in_flight}),
            )
        }
        _ => Ok(
            json!({"ok": false, "error": "refill only supports kind=environment; WarmFork snapshots must be created manually via template-create"}),
        ),
    }
}

async fn handle_pool_gc<F>(handle: &Handle<F>, req: &Value) -> anyhow::Result<Value>
where
    F: VMFactory + Sync + Send + 'static,
    F::VM: VM + Snapshottable + Sync + Send + 'static,
{
    let pool = handle
        .pool
        .as_ref()
        .ok_or_else(|| anyhow!("template pool not configured"))?;

    let kind_str = match req["kind"].as_str() {
        Some(k) => k.to_string(),
        None => {
            return Ok(json!({"ok": false, "error": "missing required field 'kind'"}));
        }
    };
    let template_id = match req["template_id"].as_str() {
        Some(id) => id.to_string(),
        None => {
            return Ok(json!({"ok": false, "error": "missing required field 'template_id'"}));
        }
    };

    if kind_str == "continuation" {
        return Ok(json!({
            "ok": false,
            "error": "Continuation snapshots are managed by the continuation store, not the template pool. \
                      Use continuation-delete to remove a specific entry."
        }));
    }

    let expected_kind = match kind_str.as_str() {
        "environment" => SnapshotType::Environment,
        "warm_fork" => SnapshotType::WarmFork,
        _ => {
            return Ok(
                json!({"ok": false, "error": format!("unknown kind '{}'; use environment or warm_fork", kind_str)}),
            );
        }
    };

    match pool.remove_by_id(&template_id, &expected_kind).await {
        Err(e) => Ok(json!({"ok": false, "error": e.to_string()})),
        Ok(false) => {
            Ok(json!({"ok": false, "error": format!("template {} not found in pool", template_id)}))
        }
        Ok(true) => {
            let remaining = pool.total_depth().await;
            Ok(json!({"ok": true, "kind": kind_str, "removed": 1, "remaining": remaining}))
        }
    }
}

async fn handle_continuation_list<F>(handle: &Handle<F>) -> anyhow::Result<Value>
where
    F: VMFactory + Sync + Send + 'static,
    F::VM: VM + Snapshottable + Sync + Send + 'static,
{
    let store = handle
        .continuation_store
        .as_ref()
        .ok_or_else(|| anyhow!("continuation store not configured"))?;
    let entries = store.list().await;
    let items: Vec<Value> = entries
        .iter()
        .map(|t| {
            let (pod_uid, generation) = t
                .workload_identity
                .as_ref()
                .map(|wi| (wi.pod_uid.as_str(), wi.generation))
                .unwrap_or(("", 0));
            json!({
                "template_id": t.id,
                "pod_uid": pod_uid,
                "generation": generation,
                "created_at_secs": t.created_at_secs,
                "snapshot_dir": t.snapshot_dir,
            })
        })
        .collect();
    Ok(json!({"ok": true, "entries": items}))
}

async fn handle_continuation_delete<F>(handle: &Handle<F>, req: &Value) -> anyhow::Result<Value>
where
    F: VMFactory + Sync + Send + 'static,
    F::VM: VM + Snapshottable + Sync + Send + 'static,
{
    let store = handle
        .continuation_store
        .as_ref()
        .ok_or_else(|| anyhow!("continuation store not configured"))?;
    let pod_uid = req["pod_uid"]
        .as_str()
        .ok_or_else(|| anyhow!("missing pod_uid"))?
        .to_string();
    let generation: u32 = match req["generation"].as_u64() {
        None => 0,
        Some(v) if v <= u32::MAX as u64 => v as u32,
        Some(v) => {
            return Err(anyhow!(
                "generation {} exceeds u32::MAX; refusing continuation-delete",
                v
            ));
        }
    };
    let identity = WorkloadIdentity {
        pod_uid,
        generation,
    };
    let removed = store.delete(&identity).await?;
    Ok(
        json!({"ok": true, "removed": removed, "pod_uid": identity.pod_uid, "generation": identity.generation}),
    )
}

/// Snapshot a running sandbox's VM and add the result to the template pool.
///
/// The sandbox's VM is paused, snapshotted, and immediately resumed so the
/// original container continues running.
///
/// `key` is the user-supplied pool key; pods with `kuasar.io/template-key=<key>`
/// will be matched to this template at start time.
async fn create_from_sandbox<F>(
    handle: &Handle<F>,
    sandbox_id: &str,
    template_id: &str,
    key: &str,
    snapshot_type: SnapshotType,
    workload_identity: Option<WorkloadIdentity>,
) -> Result<PooledTemplate>
where
    F: VMFactory + Sync + Send + 'static,
    F::VM: VM + Snapshottable + Sync + Send + 'static,
{
    // For Continuation, we need continuation_store. For WarmFork, we need pool.
    let pool_opt = handle.pool.as_ref();
    if !matches!(snapshot_type, SnapshotType::Continuation) {
        pool_opt.ok_or_else(|| anyhow!("template pool not configured"))?;
    }
    let sandbox_mutex = handle
        .sandboxes
        .read()
        .await
        .get(sandbox_id)
        .ok_or_else(|| anyhow!("sandbox {} not found", sandbox_id))?
        .clone();

    let mut sandbox = sandbox_mutex.lock().await;
    if !matches!(sandbox.status, SandboxStatus::Running(_)) {
        return Err(anyhow!(
            "template-create requires sandbox {} to be running, current status: {:?}",
            sandbox_id,
            sandbox.status
        )
        .into());
    }

    // Both WarmFork and Continuation require virtio-blk: virtiofs shares container layers via a
    // vhost-user socket bound to a specific virtiofsd process, whose file descriptors
    // cannot be transferred across the snapshot/restore boundary.
    if sandbox.vm.container_storage_backend() != VIRTIO_BLK {
        return Err(anyhow!(
            "WarmFork/Continuation snapshots require container_storage_backend=virtio-blk; \
             current type '{}' cannot be snapshotted with active containers.",
            sandbox.vm.container_storage_backend()
        )
        .into());
    }

    // WarmFork-specific pre-snapshot checks: the process must already be blocking on the
    // readiness socket before vm.snapshot() pauses the VM.  Checking after snapshot would
    // allow a non-ready process to be frozen and later injected, producing a sandbox that
    // executes from an undefined state.
    let warmfork_check_result = if matches!(snapshot_type, SnapshotType::WarmFork) {
        let protocol_version = sandbox
            .data
            .config
            .as_ref()
            .and_then(|cfg| cfg.annotations.get(ANNOTATION_WARM_FORK_READY_PROTOCOL))
            .cloned()
            .unwrap_or_default();
        if protocol_version != WARM_FORK_PROTOCOL_V1 {
            return Err(anyhow!(
                "sandbox {}: cannot create WarmFork template — pod annotation '{}={}' is required; \
                 found: '{}'",
                sandbox_id,
                ANNOTATION_WARM_FORK_READY_PROTOCOL,
                WARM_FORK_PROTOCOL_V1,
                protocol_version,
            )
            .into());
        }
        // Verify all readiness sockets are open and workloads speak the expected protocol.
        // check_inject_socket() probes each target container's socket, confirming the
        // process is in the ready-waiting state before vm.snapshot() pauses the VM.
        let annotations = sandbox.data.config.as_ref().map(|c| &c.annotations);
        let pod_socket = annotations
            .and_then(|a| a.get(ANNOTATION_WARM_FORK_READINESS_SOCKET))
            .map(|s| s.as_str())
            .unwrap_or(ANNOTATION_WARM_FORK_DEFAULT_READINESS_SOCKET);

        // Build a name→container_id reverse map from the running containers' OCI specs.
        // Kubernetes sets "io.kubernetes.container.name" in the OCI spec annotations.
        let name_to_cid: HashMap<String, String> = sandbox
            .containers
            .iter()
            .filter_map(|(cid, container)| {
                container
                    .data
                    .spec
                    .as_ref()
                    .and_then(|s| s.annotations.get("io.kubernetes.container.name"))
                    .map(|name| (name.clone(), cid.clone()))
            })
            .collect();

        let (check_targets, resolved_warm_fork_targets): (
            Vec<vmm_common::api::sandbox::InjectTarget>,
            Vec<WarmForkTarget>,
        ) = if let Some(names) = annotations
            .map(parse_warm_fork_container_names)
            .transpose()
            .map_err(|e| {
                anyhow!(
                    "sandbox {}: invalid WarmFork target annotation: {}",
                    sandbox_id,
                    e
                )
            })?
            .flatten()
        {
            let mut check_targets = Vec::with_capacity(names.len());
            let mut wf_targets = Vec::with_capacity(names.len());
            for name in names {
                let socket = annotations
                    .and_then(|a| {
                        a.get(&format!(
                            "kuasar.io/container/{}/warm-fork-readiness-socket",
                            &name
                        ))
                    })
                    .cloned()
                    .unwrap_or_else(|| pod_socket.to_string());
                // Container name must resolve to a CRI container ID; fall back only fails hard.
                let container_id = match name_to_cid.get(&name) {
                    Some(id) => id.clone(),
                    None => {
                        return Err(anyhow!(
                            "sandbox {}: WarmFork container '{}' not found in running sandbox — \
                             cannot resolve to a CRI container ID; ensure the container has OCI \
                             spec annotation 'io.kubernetes.container.name'",
                            sandbox_id,
                            name
                        )
                        .into());
                    }
                };
                let mut it = vmm_common::api::sandbox::InjectTarget::new();
                it.container_id = container_id.clone();
                it.socket_path = socket.clone();
                check_targets.push(it);
                wf_targets.push(WarmForkTarget {
                    container_name: name,
                    container_id,
                    socket_path: socket,
                    env_overrides: Default::default(),
                    context: String::new(),
                });
            }
            (check_targets, wf_targets)
        } else {
            let container_id =
                match sandbox.containers.len() {
                    1 => sandbox.containers.keys().next().cloned().ok_or_else(|| {
                        anyhow!("sandbox {}: no running container found", sandbox_id)
                    })?,
                    0 => {
                        return Err(anyhow!(
                        "sandbox {}: cannot create WarmFork template in single-container mode: \
                         no running container found",
                        sandbox_id
                    )
                        .into());
                    }
                    n => {
                        return Err(anyhow!(
                            "sandbox {}: WarmFork '{}' annotation is required for pods with {} \
                         containers; single-container mode requires exactly one running container",
                            sandbox_id,
                            ANNOTATION_WARM_FORK_CONTAINERS,
                            n
                        )
                        .into());
                    }
                };
            let mut it = vmm_common::api::sandbox::InjectTarget::new();
            it.container_id = container_id.clone();
            it.socket_path = pod_socket.to_string();
            (
                vec![it],
                vec![WarmForkTarget {
                    container_name: String::new(),
                    container_id,
                    socket_path: pod_socket.to_string(),
                    env_overrides: Default::default(),
                    context: String::new(),
                }],
            )
        };

        sandbox
            .check_inject_socket(&check_targets)
            .await
            .map_err(|e| {
                anyhow!(
                    "sandbox {}: WarmFork ready-check failed before snapshot: {}",
                    sandbox_id,
                    e
                )
            })?;
        Some((protocol_version, resolved_warm_fork_targets))
    } else {
        // Continuation: the process is captured as-is; no ready-waiting protocol required.
        None
    };

    // Snapshot directory: Continuation goes under continuation/{pod_uid}/g{N}/snapshot/;
    // WarmFork goes under warmfork/{template_id}/snapshot/.
    let snapshot_dir = if matches!(snapshot_type, SnapshotType::Continuation) {
        let wi = workload_identity.as_ref().ok_or_else(|| {
            anyhow!("snapshot_type=continuation requires workload_identity to be set")
        })?;
        let store = handle.continuation_store.as_ref().ok_or_else(|| {
            anyhow!("continuation store not configured (enable_continuation_restore=true required)")
        })?;
        let dir = store.entry_dir(wi).join("snapshot");
        if dir.exists() {
            return Err(anyhow!(
                "continuation snapshot for {}/g{} already exists at {}; \
                 remove it before re-snapshotting the same generation",
                wi.pod_uid,
                wi.generation,
                dir.display()
            )
            .into());
        }
        dir
    } else {
        pool_opt
            .ok_or_else(|| anyhow!("template pool not configured"))?
            .store_dir
            .join("warmfork")
            .join(template_id)
            .join("snapshot")
    };
    tokio::fs::create_dir_all(&snapshot_dir)
        .await
        .map_err(|e| anyhow!("create snapshot dir: {}", e))?;

    // Capture id_generator before snapshot so restored sandboxes start their device ID
    // counter above any IDs already embedded in the VM state (avoids IdentifierNotUnique).
    let source_id_generator = sandbox.id_generator;

    // Snapshot the storage metadata so restored instances can reuse existing block devices
    // without re-creating ext4 images.
    let storages = sandbox.storages.clone();

    // Container IDs currently tracked in this sandbox become orphans on restore.
    // Also include any orphan containers from a prior WarmFork restore that are
    // still alive in the guest but were never adopted into sandbox.containers.
    let mut orphan_container_ids: Vec<String> = sandbox.containers.keys().cloned().collect();
    for id in &sandbox.orphan_container_ids {
        if !orphan_container_ids.contains(id) {
            orphan_container_ids.push(id.clone());
        }
    }

    // Per-container snapshot metadata for cross-sandbox storage matching via lower_dirs.
    let snapshot_containers: Vec<SnapshotContainerMeta> = sandbox
        .storages
        .iter()
        .filter(|s| s.owned_by_runtime && s.device_id.is_some() && s.cleanup_path.is_some())
        .flat_map(|s| {
            let device_id = s.device_id.clone().unwrap_or_default();
            let lower_dirs = s.lower_dirs.clone().unwrap_or_default();
            let img_path = s.cleanup_path.clone().unwrap_or_default();
            let storage_id = s.id.clone();
            s.ref_container
                .keys()
                .map(|cid| SnapshotContainerMeta {
                    id: cid.clone(),
                    lower_dirs: lower_dirs.clone(),
                    storage_id: storage_id.clone(),
                    device_id: device_id.clone(),
                    img_path: img_path.clone(),
                })
                .collect::<Vec<_>>()
        })
        .collect();

    // Collect ext4 disk images that are hot-attached as virtio-blk devices.
    // These are copied into the snapshot directory while the VM is paused (inside snapshot()).
    let disks: Vec<DiskSnapshot> = sandbox
        .storages
        .iter()
        .filter(|s| s.owned_by_runtime)
        .filter_map(|s| {
            let did = s.device_id.as_ref()?;
            let img_path = s.cleanup_path.as_ref()?;
            Some(DiskSnapshot {
                storage_id: s.id.clone(),
                device_id: did.clone(),
                img_path: img_path.clone(),
            })
        })
        .collect();

    // vm.snapshot() handles pause → disk copy → CH snapshot → resume internally.
    let meta = sandbox
        .vm
        .snapshot(&snapshot_dir, &disks)
        .await
        .map_err(|e| anyhow!("snapshot sandbox {}: {}", sandbox_id, e))?;

    // Continuation: key is derived from workload identity to encode (pod_uid, generation)
    // in the pool key, preventing stale-snapshot reuse after a pod restart.
    // WarmFork: key is the operator-supplied opaque string.
    let tmpl_key = match (&snapshot_type, &workload_identity) {
        (SnapshotType::Continuation, Some(wi)) => {
            TemplateKey::from_workload_identity(&wi.pod_uid, wi.generation)
        }
        _ => TemplateKey::user(key),
    };
    let mut tmpl = PooledTemplate::new(
        template_id,
        tmpl_key,
        meta.snapshot_dir,
        handle.factory.image_path(),
        handle.factory.kernel_path(),
        handle.factory.vcpus(),
        handle.factory.memory_mb(),
        meta.original_task_vsock,
        meta.original_console_path,
    );

    let (ready_protocol_version, warm_fork_targets) = match warmfork_check_result {
        Some((pv, wft)) => (Some(pv), wft),
        None => (None, vec![]),
    };

    tmpl.snapshot_type = snapshot_type;
    tmpl.ready_protocol_version = ready_protocol_version;
    tmpl.warm_fork_targets = warm_fork_targets;
    tmpl.workload_identity = workload_identity;
    tmpl.id_generator = source_id_generator;
    tmpl.disk_images = meta.disk_images;
    tmpl.storages = storages;
    tmpl.orphan_container_ids = orphan_container_ids;
    tmpl.snapshot_containers = snapshot_containers;

    if matches!(tmpl.snapshot_type, SnapshotType::Continuation) {
        let store = handle
            .continuation_store
            .as_ref()
            .ok_or_else(|| anyhow!("continuation store not configured"))?;
        store.save(&tmpl).await?;
        info!(
            "template {}: saved to continuation store (sandbox {}, {}/g{})",
            template_id,
            sandbox_id,
            tmpl.workload_identity
                .as_ref()
                .map(|wi| wi.pod_uid.as_str())
                .unwrap_or("?"),
            tmpl.workload_identity
                .as_ref()
                .map(|wi| wi.generation)
                .unwrap_or(0),
        );
    } else {
        let pool = pool_opt.ok_or_else(|| anyhow!("template pool not configured"))?;
        pool.add(tmpl.clone()).await?;
        info!(
            "template {}: created from sandbox {} (type={:?}, pool_depth={})",
            template_id,
            sandbox_id,
            tmpl.snapshot_type,
            pool.depth(&tmpl.key).await,
        );
    }
    Ok(tmpl)
}

/// Create a bare sandbox slot in `SandboxStatus::Created` state without going through containerd.
///
/// Used by the `run` action to enable e2e testing of the restore path without a running
/// containerd/Kubernetes stack.
async fn create_sandbox_slot<F>(handle: &Handle<F>, sandbox_id: &str) -> Result<()>
where
    F: VMFactory + Sync + Send + 'static,
    F::VM: VM + Snapshottable + Sync + Send + 'static,
{
    if handle.sandboxes.read().await.contains_key(sandbox_id) {
        return Err(anyhow!("sandbox {} already exists", sandbox_id).into());
    }
    let base_dir = handle.sandbox_base_dir.join(sandbox_id);
    create_dir_all(&base_dir)
        .await
        .map_err(|e| anyhow!("create sandbox dir {:?}: {}", base_dir, e))?;
    let base_dir_str = base_dir.to_string_lossy().to_string();
    let sandbox_opt = SandboxOption {
        base_dir: base_dir_str.clone(),
        sandbox: SandboxData {
            id: sandbox_id.to_string(),
            ..Default::default()
        },
    };
    let vm = handle
        .factory
        .create_vm(sandbox_id, &sandbox_opt)
        .await
        .map_err(|e| anyhow!("create_vm for sandbox slot {}: {}", sandbox_id, e))?;
    let sandbox = KuasarSandbox {
        vm,
        id: sandbox_id.to_string(),
        status: SandboxStatus::Created,
        base_dir: base_dir_str,
        data: SandboxData {
            id: sandbox_id.to_string(),
            ..Default::default()
        },
        containers: Default::default(),
        storages: DeviceGraph::default(),
        id_generator: 0,
        network: None,
        client: Arc::new(Mutex::new(None)),
        exit_signal: Arc::new(ExitSignal::default()),
        sandbox_cgroups: SandboxCgroup::default(),
        template_id: None,
        template_snapshot_type: None,
        lease_mode: None,
        reflink_supported: None,
        memory_restore_mode: None,
        orphan_container_ids: vec![],
    };
    sandbox.setup_sandbox_files().await?;
    sandbox.dump().await?;
    handle
        .sandboxes
        .write()
        .await
        .insert(sandbox_id.to_string(), Arc::new(Mutex::new(sandbox)));
    info!("service:created sandbox slot {} for run", sandbox_id);
    Ok(())
}

/// Stop a running sandbox, release its template lease, and delete its directory.
///
/// Mirrors the `KuasarSandboxer::delete` path but runs entirely through the admin socket,
/// so it works for sandboxes created by the `run` action without containerd involvement.
async fn destroy_sandbox<F>(handle: &Handle<F>, sandbox_id: &str) -> Result<()>
where
    F: VMFactory + Sync + Send + 'static,
    F::VM: VM + Snapshottable + Sync + Send + 'static,
{
    let sandbox_mutex = handle
        .sandboxes
        .read()
        .await
        .get(sandbox_id)
        .cloned()
        .ok_or_else(|| anyhow!("sandbox {} not found", sandbox_id))?;

    let base_dir;
    let consumed_template_id;
    let template_snapshot_type;
    let lease_mode;
    let memory_restore_mode;

    {
        let mut sandbox = sandbox_mutex.lock().await;
        base_dir = sandbox.base_dir.clone();
        consumed_template_id = sandbox.template_id.clone();
        template_snapshot_type = sandbox.template_snapshot_type.clone();
        lease_mode = sandbox.lease_mode.clone();
        memory_restore_mode = sandbox.memory_restore_mode.clone();

        sandbox
            .stop(true)
            .await
            .map_err(|e| anyhow!("stop sandbox {}: {}", sandbox_id, e))?;

        // Admin-created sandboxes have an empty cgroup_parent_path; skip cgroup removal.
        if !sandbox.sandbox_cgroups.cgroup_parent_path.is_empty()
            && !cgroups_rs::hierarchies::is_cgroup2_unified_mode()
        {
            if let Err(e) = sandbox.sandbox_cgroups.remove_sandbox_cgroups() {
                warn!("service:destroy {}: remove cgroups: {}", sandbox_id, e);
            }
        }
    }

    cleanup_mounts(&base_dir).await?;
    if let Err(e) = remove_dir_all(&base_dir).await {
        if e.kind() != ErrorKind::NotFound {
            return Err(anyhow!("remove sandbox dir {}: {}", base_dir, e).into());
        }
    }

    if let (Some(tid), Some(pool)) = (consumed_template_id, handle.pool.as_ref()) {
        match template_snapshot_type.as_ref() {
            Some(SnapshotType::Environment) => {
                if !matches!(
                    memory_restore_mode.as_ref(),
                    Some(MemoryRestoreMode::Copy) | None
                ) {
                    pool.deref(&tid).await;
                }
            }
            Some(SnapshotType::WarmFork) => match lease_mode {
                Some(TemplateLeaseMode::Exclusive) => pool.cleanup_consumed(&tid).await,
                Some(TemplateLeaseMode::Shared) => pool.deref(&tid).await,
                None => pool.cleanup_consumed(&tid).await,
            },
            Some(SnapshotType::Continuation) => {
                // Continuation snapshots are managed by ContinuationStore; no pool cleanup needed.
            }
            None => pool.cleanup_consumed(&tid).await,
        }
    }

    handle.sandboxes.write().await.remove(sandbox_id);
    info!("service:destroyed sandbox {}", sandbox_id);
    Ok(())
}

/// Restore an already-created sandbox from a WarmFork pool template.
///
/// `key` selects the latest template for that pool key; `template_id` pins to a
/// specific template by ID.  When both are provided they must match.
/// Runs in autonomous mode (`task_id = None`): the ready-waiting process self-starts
/// after COMMIT without an external injection.
async fn restore_sandbox_warm_fork<F>(
    handle: &Handle<F>,
    sandbox_id: &str,
    key: Option<&str>,
    template_id: Option<&str>,
) -> Result<String>
where
    F: VMFactory + Sync + Send + 'static,
    F::VM: VM + Snapshottable + Sync + Send + 'static,
{
    let sandbox_mutex = handle
        .sandboxes
        .read()
        .await
        .get(sandbox_id)
        .ok_or_else(|| anyhow!("sandbox {} not found", sandbox_id))?
        .clone();

    let mut sandbox = sandbox_mutex.lock().await;
    if !matches!(sandbox.status, SandboxStatus::Created) {
        return Err(anyhow!(
            "restore requires sandbox {} to be in Created state, current: {:?}",
            sandbox_id,
            sandbox.status
        )
        .into());
    }

    let pool = handle
        .pool
        .as_ref()
        .ok_or_else(|| anyhow!("template pool not configured"))?;

    // Acquire the template: by ID (with optional key verification) or by key.
    let (tmpl, acquired_template_id, lease_mode, lease) = if let Some(tid) = template_id {
        let raw = pool
            .acquire_by_id_for_restore(tid)
            .await
            .ok_or_else(|| anyhow!("WarmFork template '{}' not available for restore", tid))?;
        if raw.snapshot_type != SnapshotType::WarmFork {
            return Err(anyhow!(
                "template '{}' has snapshot_type {:?}; expected warm_fork",
                tid,
                raw.snapshot_type
            )
            .into());
        }
        let lm = pool.lease_mode.clone();
        let lease = TemplateLease::new(pool.clone(), raw.clone());
        let t = match lease.template() {
            Ok(t) => t.clone(),
            Err(e) => {
                lease.fail().await;
                return Err(e);
            }
        };
        if let Some(k) = key {
            let expected = TemplateKey::user(k);
            if t.key.key != expected.key {
                lease.fail().await;
                return Err(anyhow!(
                    "warm_fork template '{}' key '{}' does not match requested key '{}'",
                    tid,
                    t.key.key,
                    k
                )
                .into());
            }
        }
        let id = t.id.clone();
        (t, id, lm, lease)
    } else {
        let k = key.unwrap();
        let tkey = TemplateKey::user(k);
        let raw = pool
            .acquire_for_restore(&tkey)
            .await
            .ok_or_else(|| anyhow!("no WarmFork template available for key '{}'", k))?;
        if raw.snapshot_type != SnapshotType::WarmFork {
            return Err(anyhow!(
                "template for key '{}' has snapshot_type {:?}; expected WarmFork",
                k,
                raw.snapshot_type
            )
            .into());
        }
        let lm = pool.lease_mode.clone();
        let id = raw.id.clone();
        let lease = TemplateLease::new(pool.clone(), raw.clone());
        let t = lease.template()?.clone();
        (t, id, lm, lease)
    };
    let base_dir = sandbox.base_dir.clone();
    let work_dir = PathBuf::from(format!("{}/restore", base_dir));
    let memory_restore_mode = handle.snapshot_config.default_memory_restore_mode.clone();

    // Autonomous mode: task_id = None, so the ready-waiting process self-starts after COMMIT.
    // Targets carry the snapshot-time container_id already; no overlay step needed.
    let warm_fork_params = WarmForkParams {
        task_id: None,
        targets: tmpl.warm_fork_targets.clone(),
        prepare_timeout_ms: 10_000,
        commit_timeout_ms: 5_000,
    };

    if !sandbox.data.netns.is_empty() {
        if let Err(e) = sandbox.prepare_network().await {
            lease.fail().await;
            sandbox.destroy_network().await;
            return Err(e);
        }
    }

    sandbox.template_id = Some(acquired_template_id.clone());
    sandbox.template_snapshot_type = Some(SnapshotType::WarmFork);
    sandbox.lease_mode = Some(lease_mode.clone());
    sandbox.reflink_supported = Some(pool.reflink_supported);
    sandbox.id_generator = tmpl.id_generator;

    let src = RestoreSource {
        snapshot_dir: tmpl.snapshot_dir,
        work_dir,
        overrides: SnapshotPathOverrides::from_original(
            &base_dir,
            &tmpl.original_task_vsock,
            sandbox_id,
        ),
        lease_mode,
        snapshot_type: SnapshotType::WarmFork,
        disk_images: tmpl.disk_images,
        storages: tmpl.storages,
        orphan_container_ids: tmpl.orphan_container_ids,
        memory_restore_mode,
        reflink_supported: pool.reflink_supported,
        warm_fork_params: Some(warm_fork_params),
    };

    if let Err(e) = sandbox.start_from_snapshot(src).await {
        sandbox.clear_template_restore_state();
        sandbox.destroy_network().await;
        lease.fail().await;
        return Err(e);
    }

    monitor(sandbox_mutex.clone());

    if !sandbox.sandbox_cgroups.cgroup_parent_path.is_empty() {
        if let Err(e) = sandbox.add_to_cgroup().await {
            sandbox.clear_template_restore_state();
            if let Err(re) = sandbox.stop(true).await {
                warn!(
                    "service:sandbox {} rollback add_to_cgroup after WarmFork restore: {}",
                    sandbox_id, re
                );
            }
            sandbox.destroy_network().await;
            lease.fail().await;
            return Err(e);
        }
    }

    if let Err(e) = sandbox.dump().await {
        sandbox.clear_template_restore_state();
        if let Err(re) = sandbox.stop(true).await {
            warn!(
                "service:sandbox {} rollback dump after WarmFork restore: {}",
                sandbox_id, re
            );
        }
        sandbox.destroy_network().await;
        lease.fail().await;
        return Err(e);
    }

    lease.complete().await;
    info!(
        "service:sandbox {} restored from WarmFork template {} (key={}, template_id={})",
        sandbox_id,
        acquired_template_id,
        key.unwrap_or("-"),
        template_id.unwrap_or("-"),
    );
    Ok(acquired_template_id)
}

/// Restore an already-created sandbox from a Continuation snapshot by workload identity.
///
/// Unlike Environment and WarmFork, Continuation preserves the original network identity —
/// the operator is responsible for migrating the network externally before calling this.
/// `prepare_network` is intentionally skipped; on failure `destroy_network` is not called
/// for the same reason.
async fn restore_sandbox_continuation<F>(
    handle: &Handle<F>,
    sandbox_id: &str,
    pod_uid: &str,
    generation: u32,
) -> Result<String>
where
    F: VMFactory + Sync + Send + 'static,
    F::VM: VM + Snapshottable + Sync + Send + 'static,
{
    let sandbox_mutex = handle
        .sandboxes
        .read()
        .await
        .get(sandbox_id)
        .ok_or_else(|| anyhow!("sandbox {} not found", sandbox_id))?
        .clone();

    let mut sandbox = sandbox_mutex.lock().await;
    if !matches!(sandbox.status, SandboxStatus::Created) {
        return Err(anyhow!(
            "restore requires sandbox {} to be in Created state, current: {:?}",
            sandbox_id,
            sandbox.status
        )
        .into());
    }

    let store = handle
        .continuation_store
        .as_ref()
        .ok_or_else(|| anyhow!("continuation store not configured"))?;

    let identity = WorkloadIdentity {
        pod_uid: pod_uid.to_string(),
        generation,
    };
    let lease = store.acquire(&identity).await.ok_or_else(|| {
        anyhow!(
            "no continuation snapshot available for pod_uid='{}' generation={}",
            pod_uid,
            generation
        )
    })?;

    let tmpl = lease.template()?.clone();
    let acquired_template_id = tmpl.id.clone();
    let base_dir = sandbox.base_dir.clone();
    let work_dir = PathBuf::from(format!("{}/restore", base_dir));
    let memory_restore_mode = handle.snapshot_config.default_memory_restore_mode.clone();
    let reflink_supported = handle
        .pool
        .as_ref()
        .map(|p| p.reflink_supported)
        .unwrap_or(false);

    sandbox.template_id = Some(acquired_template_id.clone());
    sandbox.template_snapshot_type = Some(SnapshotType::Continuation);
    sandbox.lease_mode = Some(TemplateLeaseMode::Exclusive);
    sandbox.reflink_supported = Some(reflink_supported);
    sandbox.id_generator = tmpl.id_generator;

    let src = RestoreSource {
        snapshot_dir: tmpl.snapshot_dir,
        work_dir,
        overrides: SnapshotPathOverrides::from_original(
            &base_dir,
            &tmpl.original_task_vsock,
            sandbox_id,
        ),
        lease_mode: TemplateLeaseMode::Exclusive,
        snapshot_type: SnapshotType::Continuation,
        disk_images: tmpl.disk_images,
        storages: tmpl.storages,
        orphan_container_ids: tmpl.orphan_container_ids,
        memory_restore_mode,
        reflink_supported,
        warm_fork_params: None,
    };

    if let Err(e) = sandbox.start_from_snapshot(src).await {
        sandbox.clear_template_restore_state();
        lease.fail().await;
        return Err(e);
    }

    monitor(sandbox_mutex.clone());

    if !sandbox.sandbox_cgroups.cgroup_parent_path.is_empty() {
        if let Err(e) = sandbox.add_to_cgroup().await {
            sandbox.clear_template_restore_state();
            if let Err(re) = sandbox.stop(true).await {
                warn!(
                    "service:sandbox {} rollback add_to_cgroup after continuation restore: {}",
                    sandbox_id, re
                );
            }
            lease.fail().await;
            return Err(e);
        }
    }

    if let Err(e) = sandbox.dump().await {
        sandbox.clear_template_restore_state();
        if let Err(re) = sandbox.stop(true).await {
            warn!(
                "service:sandbox {} rollback dump after continuation restore: {}",
                sandbox_id, re
            );
        }
        lease.fail().await;
        return Err(e);
    }

    lease.complete().await;
    info!(
        "service:sandbox {} restored from continuation snapshot {}/g{} (template {})",
        sandbox_id, pod_uid, generation, acquired_template_id
    );
    Ok(acquired_template_id)
}
