[package]
name = "vmm-common"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"

[dependencies]
containerd-sandbox = { git = "https://github.com/kuasar-io/rust-extensions.git" }
serde = "1.0.139"
lazy_static = "1.4.0"
nix = "0.24.1"
anyhow = "1.0.66"
log = { version = "0.4.17", features = ["std"] }
ttrpc = { version = "0.7", features = ["async"] }
protobuf = "3.2"
async-trait = "0.1"
regex = "1.5.6"
futures = { version = "0.3.21" }
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }

tracing = "0.1.40"
tracing-opentelemetry = "0.21.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

opentelemetry = { version = "0.20.0", features = ["rt-tokio"] }
opentelemetry-otlp = "0.13.0"

[build-dependencies]
ttrpc-codegen = { git = "https://github.com/kuasar-io/ttrpc-rust.git", branch = "v0.7.1-kuasar" }
tonic-build = "0.7.2"
