[licenses]
allow = [
    "MIT",
    "CC0-1.0",
    "ISC",
    "OpenSSL",
    "Unlicense",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "Zlib",
    "BSL-1.0",
    "Unicode-DFS-2016"
]

unlicensed = "warn"
default = "warn"

private = { ignore = true }